version: '3.3'
volumes:
  data:
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=lookmoveis
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
    volumes:
      - data:/var/lib/postgres

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
