module.exports = {
  actions: {
    new: 'Novo Registro',
    edit: 'Editar',
    show: 'Visualizar',
    delete: 'Remover',
    search: 'Buscar',
    bulkDelete: 'Deletar selecionados',
    reset: 'Limpar',
    addImage: 'Adicionar Imagem',
    list: 'Listagem',
    navigation: 'Navegação',
    addAttrs: 'Adicionar Atributos',
  },
  buttons: {
    navigation: 'Navegação',
    list: 'Listagem',
    save: 'Salvar',
    filter: 'Filtrar',
    reset: 'Limpar',
    filters: 'Filtros',
    apply: 'Salvar',
    addNewItem: 'Adicionar novo',
    applyChanges: 'Aplicar',
    resetFilter: 'Restaurar',
    confirmRemovalMany: 'Confirma que deseja remover {{count}} itens',
    confirmRemovalMany_plural:
      'Confirma que deseja remover {{count}} itens',
    logout: 'Sair',
    createFirstRecord: 'Crie seu primeiro',
  },
  properties: {
    navigation: 'Navegação',
    name: 'Nome',
    clientId: 'Cliente',
    state: 'Estado',
    city: 'Cidade',
    zipcode: 'Cep',
    phoneNumber: 'Telefone',
    doc: 'Documento',
    firstName: 'Nome',
    createdAt: 'Data de criação',
    price: 'Preço',
    length: 'Comprimento',
    heigth: 'Altura',
    width: 'Largura',
    weigth: 'Peso',
    weight: 'Peso',
    description: 'Descrição',
    note: 'Nota',
    paymentTerms: 'Parcelas',
    invoiceType: 'Tipo de pagamento',
    'invoiceType.card': 'Cartão de crédito',
    'invoiceType.bank-slip': 'Boleto',
    total: 'Valor total',
    nfNumber: 'Número da nota fiscal',
    'status.peding-approval': 'Pagamento Pendente',
    'status.confirmed': 'Confirmado',
    'status.production': 'Em produção',
    'status.canceled': 'Cancelado',
    'status.delivery': 'Em entrega',
    'status.done': 'Finalizado',
    'isAvailable.true': 'Sim',
    'isAvailable.false': 'Não',
    'stock.true': 'Sim',
    'stock.false': 'Não',
    stock: 'Em estoque',
    isAvailable: 'Disponivel',
    yes: 'Sim',
    neighborhood: 'Bairro',
    streetAdd: 'Complemento',
    streetNumber: 'Número',
    streetName: 'Rua',
    categoryId: 'Categoria',
    role: 'Tipo',
    active: 'Ativo',
    'active.true': 'Sim',
    'active.false': 'Não',
    productId: 'Produto',
    value: 'Valor',
    woodTypeId: 'Acabamento',
    welcome: 'Bem vindo',
    password: 'Senha',
  },
  labels: {
    navigation: 'Navegação',
    filters: 'Filtros',
    addresses: 'Endereços',
    clients: 'Clientes',
    users: 'Usuários',
    wood_types: 'Acabamentos',
    products: 'Produtos',
    orders: 'Pedidos',
    categories: 'Categorias',
    product_wood_types: 'Acabamentos de Produtos',
    products_attrs: 'Atributos de Produtos',
    roles: 'Tipo de Usuário',
    list: 'Listagem',
    loginWelcome: 'Look Móveis',
    pages: 'Páginas',
    selectedRecords: 'Selecionados ({{selected}})',
  },
  messages: {
    noRecords: 'Nenhum item',
    loginWelcome:
      'Painel Administrativo Look Móveis. Acesso restrito.',
    noRecordsInResource: 'Não há registros neste recurso',
    invalidCredentials: 'Credenciais inválidas, tente novamente',
    confirmDelete: 'Você realmente deseja remover esse item?',
    successfullyCreated: 'Registro criado com sucesso',
    successfullyUpdated: 'Registro atualizado com sucesso',
    successfullyDeleted: 'Registro removido com sucesso',
    successfullyBulkDeleted: 'Sucesso ao remover {{count}} items',
    successfullyBulkDeleted_plural:
      'Sucesso ao remover {{count}} items',
    noRecordsSelected: 'Você não selecionou nenhum recurso',
    error404Resource: 'Não encontrado',
    error404Action: 'Não encontrado',
    error404Record: 'Não encontrado',
  },
};
