module.exports = {
  actions: {
    new: 'Novo Registro',
    edit: 'Editar',
    show: 'Visualizar',
    delete: 'Remover',
    search: 'Buscar',
    bulkDelete: 'Deletar selecionados',
  },
  buttons: {
    save: 'Salvar',
  },
  properties: {
    name: 'Nome',
    clientId: 'Cliente',
    state: 'Estado',
    city: 'Cidade',
    zipcode: 'Cep',
    phoneNumber: 'Telefone',
    doc: 'Docuemnto',
    firstName: 'Nome',
    createdAt: 'Data de criação',
    price: 'Preço',
    length: 'Comprimento',
    heigth: 'Altura',
    width: 'Largura',
    weigth: 'Peso',
    description: 'Descrição',
    note: 'Nota',
    paymentTerms: 'Parcelas',
    invoiceType: 'Tipo de pagamento',
    'invoiceType.card': 'Cartão de crédito',
    'invoiceType.bank-slip': 'Boleto',
    total: 'Valor total',
    nfNumber: 'Número da nota fiscal',
    'status.peding-approval': 'Pagamento Pendente',
    'status.confirmed': 'Confirmado',
    'status.production': 'Em produção',
    'status.canceled': 'Cancelado',
    'status.delivery': 'Em entrega',
    'status.done': 'Finalizado',
    stock: 'Em estoque',
    isAvailable: 'Disponivel',
    yes: 'Sim',
    neighborhood: 'Bairro',
    streetAdd: 'Complemento',
    streetNumber: 'Número',
    streetName: 'Rua',
  },
};
