name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          username: ${{secrets.SSH_USER}}

          script: |
            echo "Start CI/CD..."
            cd backend
            git pull
            yarn migration:build
            yarn
            yarn app && echo "End CI/CD..."
