name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}

          script: |
            echo "Start CI/CD on ${{ secrets.SSH_HOST }}"
            cd backend
            git pull
            yarn migration:build
            yarn
            yarn app && echo "End CI/CD..."
