name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}

          script: |
            kill -9 $(lsof -t -i tcp:3333)
            cd backend
            git pull
            yarn && docker-compose up -d --build && yarn migration:build && pm2 restart look-backend

      - name: Finished
        run: |
          echo "end..."
